site_name: NanoCut Control
site_description: Documentation for the NanoCut Control application
site_author: Johannes Nilsson
repo_url: https://github.com/nwjnilsson/nanocut-control
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - CAM View: cam-view.md
  - Control View: control-view.md
  - Machine Parameters: machine-parameters.md
  - Keyboard Shortcuts: keyboard-shortcuts.md
  - Building a CNC Table: building-your-machine.md
theme:
  name: material
  logo: images/nanocut-64.png
  favicon: images/nanocut-64.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
